kind: ConfigMap
apiVersion: v1
metadata:
  name: mqwebuserconfigmap
data:
  mqwebuser.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <server>
      <featureManager>
        <feature>appSecurity-2.0</feature>
        <feature>basicAuthenticationMQ-1.0</feature>
      </featureManager>
      <enterpriseApplication id="com.ibm.mq.console">
        <application-bnd>
          <security-role name="MQWebAdmin">
            <group name="MQWebAdminGroup" realm="defaultRealm"/>
          </security-role>
        </application-bnd>
      </enterpriseApplication>
      <basicRegistry id="basic" realm="defaultRealm">
        <user name="andrew" password="andrew"/>
        <group name="MQWebAdminGroup">
          <member name="andrew"/>
        </group>
      </basicRegistry>           
      <sslDefault sslRef="mqDefaultSSLConfig"/>
    </server>
# https://www.ibm.com/docs/en/ibm-mq/9.4.x?topic=dcqmumo-configuring-mq-console-basic-registry-using-mq-operator