apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ibm-ace-operator-appset
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: z-clusters-placement
        requeueAfterSeconds: 180
  template:
    metadata:
      name: ibm-ace-operator-app-{{name}}
      annotations:
        apps.open-cluster-management.io/ocm-managed-cluster: "{{name}}"
        apps.open-cluster-management.io/ocm-managed-cluster-app-namespace: openshift-gitops
        argocd.argoproj.io/skip-reconcile: "true"
      labels:
        apps.open-cluster-management.io/pull-to-ocm-managed-cluster: "true"
        velero.io/exclude-from-backup: "true"
    spec:
      project: default
      sources:
        - repoURL: https://github.com/andrewdavies-net/gitops-components-library.git
          targetRevision: master
          path: components/operators/ibm-ace
      destination:
        namespace: openshift-operators
        server: "{{server}}"
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=false
          - PruneLast=true