apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

# DISABLE AUTO END SUFFIX - Removes the random alpha numeric ending to objects such as configMaps.
generatorOptions:
 disableNameSuffixHash: true
# DISABLE AUTO END SUFFIX end

# --- CONFIGMAP CREATOR --- create configmaps from files you've added to insert into the QMGR build/creation.
# SCRIPTS CONFIG - create a configMap that holds scripts for the queue manager service.
configMapGenerator:
- name: ~qm~-scripts-configmap
  behavior: create
  files:
  - startSERVICE-mqsc.sh
  - stopSERVICE-mqsc.sh
  - startQMGR-mqsc.sh
  - stopQMGR-mqsc.sh
# SCRIPTS CONFIG end
# --- CONFIGMAP CREATOR --- end