apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-index-claim
spec:
  storageClassName: ibmc-block-bronze
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
