apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-wide-resources-role
rules:
- apiGroups:
  - "cert-manager.io"
  resources:
  - clusterissuers
  verbs:
  - create
  - delete
  - update
  - patch
  - watch
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-wide-resources-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-wide-resources-role
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-server
  namespace: openshift-gitops
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops
