apiVersion: v1
kind: ConfigMap
metadata:
  name: kustomize-plugins-cm
  namespace: openshift-gitops
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: kustomize-with-local-plugins
    spec:
      generate:
        command: ["sh", "-c"]
        args: ["XDG_CONFIG_HOME=$(pwd | cut -d/ -f 1-3) kustomize build --enable_alpha_plugins"]