apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tenants-config
  namespace: openshift-gitops
spec:
  project: default
  destination:
    name: ''
    namespace: default
    server: https://kubernetes.default.svc
  sources:
    - repoURL: git-repo-url.git
      path: path-to-tenants-folder
      targetRevision: HEAD
