apiVersion: builtin
kind: SecretGenerator
metadata:
  name: ca-key-pair
  namespace: cert-manager
behavior: create
files:
  - tls.crt=./tls.crt
  - tls.key=./tls.key
type: kubernetes.io/tls
options:
  disableNameSuffixHash: true