apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: postgresql-operator-appset
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: all-clusters-placement
        requeueAfterSeconds: 180
  template:
    metadata:
      name: postgresql-operator-app-{{name}}
      labels:
        velero.io/exclude-from-backup: "true"
    spec:
      project: default
      source:
        repoURL: https://github.com/ldesrosi/gitops-components-library.git
        targetRevision: master
        path: components/operators/postgresql
      destination:
        namespace: openshift-operators 
        server: "{{server}}"
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=false
          - PruneLast=true