apiVersion: operators.coreos.com/v1 
kind: OperatorGroup 
metadata: 
  name: operatorgroup 
  namespace: keycloak
spec:
  targetNamespaces:
    - keycloak
  upgradeStrategy: Default
--- 
apiVersion: operators.coreos.com/v1alpha1 
kind: Subscription 
metadata: 
  name: keycloak-operator 
  namespace: keycloak
spec: 
  channel: fast 
  startingCSV: keycloak-operator.v23.0.5
  installPlanApproval: Manual
  name: keycloak-operator 
  source: community-operators
  sourceNamespace: openshift-marketplace