apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: task-console
    middleware: bamoe
  name: task-console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-console
  template:
    metadata:
      labels:
        app: task-console
    spec:
      containers:
        - env:
            - name: RUNTIME_TOOLS_TASK_CONSOLE_KOGITO_ENV_MODE
              value: PROD
            - name: RUNTIME_TOOLS_TASK_CONSOLE_DATA_INDEX_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: bamoe-services-endpoints
                  key: DATA_INDEX_URL
            - name: KOGITO_CONSOLES_KEYCLOAK_URL
              valueFrom:
                configMapKeyRef:
                  name: bamoe-services-endpoints
                  key: KEYCLOAK_URL
            - name: KOGITO_CONSOLES_KEYCLOAK_DISABLE_HEALTH_CHECK
              value: 'true'
            - name: KOGITO_CONSOLES_KEYCLOAK_REALM
              value: kogito
            - name: KOGITO_CONSOLES_KEYCLOAK_CLIENT_ID
              value: kogito-task-service
          image: quay.io/bamoe/task-console:9.1.0-ibm-0001
          name: bamoe-task-console
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
