apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-cert
spec:
  commonName: keycloak
  dnsNames:
  - keycloak
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
  secretName: keycloak-tls-secret
  subject:
    organizations:
    - [organisation]