kind: Keycloak
apiVersion: k8s.keycloak.org/v2alpha1
metadata:
  name: cluster-keycloak
  namespace: keycloak
  labels:
    app: sso
spec:
  instances: 1
  db:
    vendor: postgres
    host: keycloak-db-primary.keycloak.svc
    usernameSecret:
      name: keycloak-db-pguser-keycloak
      key: user
    passwordSecret:
      name: keycloak-db-pguser-keycloak
      key: password
  ingress:
    className: openshift-default
  http:
    tlsSecret: keycloak-tls-secret