kind: Keycloak
apiVersion: k8s.keycloak.org/v2alpha1
metadata:
  name: cluster-keycloak
  namespace: keycloak
  labels:
    app: sso

spec:
  instances: 1
  hostname:
    hostname: example.org
  http:
    tlsSecret: keycloak-tls-secret