kind: Keycloak
apiVersion: k8s.keycloak.org/v2alpha1
metadata:
  name: cluster-keycloak
  namespace: keycloak
  labels:
    app: sso
spec:
  instances: 1
  db:
    vendor: postgres
    host: 
      valueFrom: { secretKeyRef: { name: keycloak-db-pguser-keycloak-db-user, key: host } }
    usernameSecret:
      name: keycloak-db-pguser-keycloak-db-user
      key: user
    passwordSecret:
      name: keycloak-db-pguser-keycloak-db-user
      key: password
  ingress:
    className: openshift-default
  http:
    tlsSecret: keycloak-tls-secret