apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
#  name: cert
  name: ~ir~-cert
spec:
  commonName: ~ir~
  dnsNames:
  - ~ir~
  - ~ir~-ibm-ir
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
#  secretName: cert
  secretName: ~ir~-cert
  subject:
    organizations:
    - ~organisation~

