apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

# DISABLE AUTO END SUFFIX - Removes the random alpha numeric ending to objects such as configMaps.
generatorOptions:
 disableNameSuffixHash: true
# DISABLE AUTO END SUFFIX end

# ADD RESOURCES - add one or more 'resources' (files) for the build.  Files must be created and added to the path dictated.
resources:
- ./ace.yaml
- ./certificate.yaml