apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ocp-gitops
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: z-clusters-placement
        requeueAfterSeconds: 180
        # must be push as it installs gitops onto the remote clusters
  template:
    metadata:
      name: gitops-operator-app-{{name}}
      labels:
        velero.io/exclude-from-backup: "true"
    spec:
      project: default
      source:
        repoURL: https://github.com/andrewdavies-net/gitops-components-library.git
        targetRevision: master
        path: components/operators/gitops
      destination:
        namespace: openshift-gitops-operator
        server: "{{server}}"
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=false
          - PruneLast=true